In [1]:
#예제1 문자열에서 유니코드 코드 포인트 리스트 만들기 V1
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

#예제2 문자열에서 유니코드 코드 포인트 리스트 만들기 V2
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]
[36, 42, 38, 33, 64]


In [9]:
#예제3 지능형 리스트 지역 변수와 주변 변수 구분 예제
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

#예제4 지능형 리스트로 만든 리스트
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

#예제5 map()/filter()로 만든 리스트
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

#예제6 지능형 리스트를 이용한 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirt  = [(color, size) for color in colors for size in sizes]

print(tshirt)

for color in colors:
  for size in sizes:
    print((color, size))

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]
[34, 33, 126, 36, 36, 42, 38, 33, 64]
[126] 

Map function:
>>> <map object at 0x7e40d8eff730>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]
[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [8]:
#예제7 제너레이터 표현식
import array

symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

ord_s = array.array('I', [ord(symbol) for symbol in symbols])

print(ord_s)

#예제8 제너레이터 표현식에서의 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
  print(tshirt)


(33, 35, 94, 38, 38, 35)
array('I', [33, 35, 94, 38, 38, 35])
black S
white S
black M
white M
black L
white L


In [11]:
#에제9. 레코드로 사용된 튜플
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

#예제10. 레코드로 사용된 튜플2
for country, _ in traveler_ids:
  print(country)

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855
USA
BRA
ESP


In [13]:
#예제11. 튜플 병렬 할당
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

#예제12. 튜플 병렬 할당(swap)
a=10; b=20
b, a = a, b
print(a, b)

33.9425
-118.408056
20 10


In [14]:
#예제13. 튜플 변렬 할당(함수 인수 전달)
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)

(2, 4)
(2, 4)
2 4


In [15]:
#예제14. 파일시스템 경로에서 경로명과 파일명 추출
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)

idrsa.pub


In [17]:
#예제15. *사용으로 병렬 할당 언패킹1
a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)


0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [18]:
#예제16 *사용으로 병렬 할당 언패킹2
a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


In [21]:
#예제17. longitude에 접근하기 위해 내포된 튜플 언패킹
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [23]:
#예제18. 명명된 튜플형을 정의하고 사용하기
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139,691))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

#예제19
print(City._fields)

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208
                                                 ))
delhi = City._make(delhi_data)
print(delhi._asdict())

for key, value in delhi._asdict().items():
  print(key + ':', value)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139, 691))
36.933
(35.689, 139, 691)
JP
('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [24]:
#예제20. 슬라이싱 예제
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


In [29]:
#예제21. 단순 텍스트 파일 청구서의 행 항목들
invoice = """
0.....6..................25.........33......40.......
1909  Pimoroni              $17.50     3     $52.50
1489  6mm Tactile           $4.95      2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

     $52.50 Pimoroni              $17.50     3
     $9.90 6mm Tactile           $4.95      2
 


In [30]:
#예제22. 가변 시퀀스 변형
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


In [31]:
#예제23. 가변 시퀀스 변형 오류 예시
# l[2:5] = 100

#예제24. 올바른 할당문
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [32]:
#예제25. 시퀀스에 덧셈 곱셈 수행
l = [1,2,3]
print(l * 5)
print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


In [34]:
#예제26. 길이가 3인 리스트 3개로 표현한 틱택토 보드
borad = [['_'] * 3 for i in range(3)]
print(borad)

borad[1][2] = 'X'
print(borad)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [35]:
#예제27. 동일한 리스트에 대한 세 개의 참조를 가진 리스트
weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board[1][2] = 'O'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [36]:
#예제28. 동일한 리스트에 대한 세 개의 참조를 가진 리스트2
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'
print(board)

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]


In [37]:
#예제29. [예제26]의 지능형 리스트의 다른 표현
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)
board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [39]:
#에제30. 가변 시퀀스의 복합 할당 연산자 곱 결과
l = [1,2,3]
print(id(l))

l *= 2
print(l)

print(id(l))

#에제31. 불변 시퀀스의 복합 할당 연산자 곱 결과

t = (1,2,3)
print(id(t))

t *= 2
print(id(t))

138816980995328
[1, 2, 3, 1, 2, 3]
138816980995328
138816982911616
138816982580192


In [43]:
#예제32 퀴즈

t = (1,2, [30,40])
print(t)


t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [44]:
#예제33. 퀴즈 수행 결과
print(t)

(1, 2, [30, 40, 50, 60])


In [45]:
#34. 리스트 정렬: sorted()

fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))

print(sorted(fruits, reverse=True))

print(sorted(fruits, key=len))

#예제35. 리스트 정렬: list.sort()
print(sorted(fruits, key=len, reverse=True))
print(fruits)

fruits.sort()
print(fruits)

['apple', 'banana', 'grape', 'raspberry']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']
['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


In [47]:
#예제36. 커다란 실수 배열의 생성
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
print(floats[-1])

#예제37. 커다란 실수 배열의 저장/로딩
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

print(floats2[-1])

print(floats2 == floats)

0.6457591261577905
0.6457591261577905
True


In [48]:
#에제 38. 배열 항목 값의 바이트 중 하나 변경
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))

print(memv[0])

memv_oct = memv.cast('B')
print(memv_oct.tolist())

memv_oct[5] = 4
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [49]:
#예제39. numpy.ndarray에서 행과 열을 이용한 기본 연산
import numpy
a = numpy.arange(12)
print(a)

print(type(a))

#예제40. numpy.ndarray에서 행과 열을 이용한 기본 연산2
print(a.shape)

a.shape = 3, 4
print(a)

#예제 41. numpy.ndarray에서 행과 열을 이용한 기본 연산3
print(a[2])

print(a[2,1])

print(a[:, 1])

#예제 42. numpy.ndarray에서 행과 열을 이용한 기본 연산4
print(a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [50]:
#예제 43. 덱 이용하기1

from collections import deque
dq = deque(range(10), maxlen=10)
print(dq)

dq.rotate(3)
print(dq)

dq.rotate(-4)
print(dq)

#예제 44. 덱 이용하기2
dq.appendleft(-1)
print(dq)

dq.extend([11, 22, 33])
print(dq)

dq.extendleft([10, 20, 30, 40])
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
